### ISSUE TITLE
cljs-priority-map is no longer compatible with ClojureScript v1.9.854

### ISSUE THREAD

**Issue by alexanderkiel** [mmb90/cljs-cache#1]
Please see here: https://github.com/tailrecursion/cljs-priority-map/issues/10

**Comment by burbma** [comment]
Thanks for pointing this out. Let's see if the PR on cljs-priority-map gets worked out soon.

**Comment by va511e** [comment]
Issue closed in cljs-priority-map in version 1.2.1. PR created #2. Can you please merge and release a new jar? Thank you.

**Comment by burbma** [comment]
Should be good to go with `[org.clojars.mmb90/cljs-cache "0.1.4"]`

**Comment by va511e** [comment]
Thank you!
